command:
  - streamlit
  - run
  - app.py
  - --server.address=0.0.0.0
  - --server.port=8000
  - --server.headless=true
  - --browser.gatherUsageStats=false
env:
  - name: ENDPOINT_NAME
    value: projects/new-database/branches/production/endpoints/primary
  - name: LOG_LEVEL
    value: INFO
