CREATE SCHEMA IF NOT EXISTS tariff;

CREATE TABLE IF NOT EXISTS tariff.app_diagnostics (
    diagnostic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(320) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS app_diagnostics_created_idx
    ON tariff.app_diagnostics(created_at DESC, diagnostic_id DESC);

CREATE TABLE IF NOT EXISTS tariff.policy_notice_snapshots (
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_identifier VARCHAR(200) NOT NULL,
    title VARCHAR(500) NOT NULL,
    agency VARCHAR(300) NOT NULL,
    canonical_url TEXT NOT NULL,
    publication_date DATE,
    retrieved_at TIMESTAMPTZ NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (source_identifier, content_sha256)
);

CREATE INDEX IF NOT EXISTS policy_notice_snapshots_published_idx
    ON tariff.policy_notice_snapshots(publication_date DESC, notice_id DESC);
