CREATE SCHEMA IF NOT EXISTS tariff;

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS tariff.app_diagnostics (
    diagnostic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(320) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS app_diagnostics_created_idx
    ON tariff.app_diagnostics(created_at DESC, diagnostic_id DESC);

CREATE TABLE IF NOT EXISTS tariff.policy_notice_snapshots (
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_identifier VARCHAR(200) NOT NULL,
    title VARCHAR(500) NOT NULL,
    agency VARCHAR(300) NOT NULL,
    canonical_url TEXT NOT NULL,
    publication_date DATE,
    effective_date DATE,
    retrieved_at TIMESTAMPTZ NOT NULL,
    raw_content TEXT NOT NULL,
    normalized_text TEXT NOT NULL,
    raw_payload JSONB NOT NULL,
    source_provenance TEXT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    analysis_state VARCHAR(30) NOT NULL DEFAULT 'unassessed',
    UNIQUE (source_identifier, content_sha256)
);

ALTER TABLE tariff.policy_notice_snapshots
    ADD COLUMN IF NOT EXISTS effective_date DATE,
    ADD COLUMN IF NOT EXISTS raw_content TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS normalized_text TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS raw_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS source_provenance TEXT NOT NULL DEFAULT 'Federal Register API',
    ADD COLUMN IF NOT EXISTS analysis_state VARCHAR(30) NOT NULL DEFAULT 'unassessed';

CREATE INDEX IF NOT EXISTS policy_notice_snapshots_published_idx
    ON tariff.policy_notice_snapshots(publication_date DESC, notice_id DESC);

CREATE TABLE IF NOT EXISTS tariff.policy_notice_chunks (
    chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id BIGINT NOT NULL REFERENCES tariff.policy_notice_snapshots(notice_id),
    chunk_index INTEGER NOT NULL CHECK (chunk_index >= 0),
    section_title VARCHAR(300),
    chunk_text TEXT NOT NULL,
    start_offset INTEGER NOT NULL CHECK (start_offset >= 0),
    end_offset INTEGER NOT NULL CHECK (end_offset > start_offset),
    hts_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    UNIQUE (notice_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS policy_notice_chunks_notice_idx
    ON tariff.policy_notice_chunks(notice_id, chunk_index);

CREATE TABLE IF NOT EXISTS tariff.policy_notice_embeddings (
    chunk_id BIGINT PRIMARY KEY REFERENCES tariff.policy_notice_chunks(chunk_id),
    embedding VECTOR(1024) NOT NULL,
    endpoint_name VARCHAR(300) NOT NULL,
    model_version VARCHAR(300) NOT NULL,
    embedded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS policy_notice_embeddings_hnsw_idx
    ON tariff.policy_notice_embeddings USING hnsw (embedding vector_cosine_ops);

CREATE TABLE IF NOT EXISTS tariff.scenario_versions (
    scenario_version VARCHAR(64) PRIMARY KEY,
    scenario_name VARCHAR(300) NOT NULL,
    measurement_period VARCHAR(100) NOT NULL,
    provenance_label VARCHAR(100) NOT NULL,
    source_citation TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tariff.enterprise_segments (
    scenario_version VARCHAR(64) NOT NULL,
    segment_key VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    provenance_label VARCHAR(100) NOT NULL,
    source_name VARCHAR(300) NOT NULL,
    source_url TEXT,
    source_citation TEXT NOT NULL,
    PRIMARY KEY (scenario_version, segment_key),
    FOREIGN KEY (scenario_version) REFERENCES tariff.scenario_versions(scenario_version)
);

CREATE TABLE IF NOT EXISTS tariff.product_lines (
    scenario_version VARCHAR(64) NOT NULL,
    product_line_key VARCHAR(100) NOT NULL,
    segment_key VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    provenance_label VARCHAR(100) NOT NULL,
    source_name VARCHAR(300) NOT NULL,
    source_url TEXT,
    source_citation TEXT NOT NULL,
    PRIMARY KEY (scenario_version, product_line_key),
    FOREIGN KEY (scenario_version, segment_key)
        REFERENCES tariff.enterprise_segments(scenario_version, segment_key)
);

CREATE TABLE IF NOT EXISTS tariff.components (
    scenario_version VARCHAR(64) NOT NULL,
    component_key VARCHAR(100) NOT NULL,
    name VARCHAR(300) NOT NULL,
    provenance_label VARCHAR(100) NOT NULL,
    source_name VARCHAR(300) NOT NULL,
    source_url TEXT,
    source_citation TEXT NOT NULL,
    PRIMARY KEY (scenario_version, component_key),
    FOREIGN KEY (scenario_version) REFERENCES tariff.scenario_versions(scenario_version)
);

CREATE TABLE IF NOT EXISTS tariff.bom_relationships (
    scenario_version VARCHAR(64) NOT NULL,
    product_line_key VARCHAR(100) NOT NULL,
    component_key VARCHAR(100) NOT NULL,
    provenance_label VARCHAR(100) NOT NULL,
    source_name VARCHAR(300) NOT NULL,
    source_url TEXT,
    source_citation TEXT NOT NULL,
    PRIMARY KEY (scenario_version, product_line_key, component_key),
    FOREIGN KEY (scenario_version, product_line_key)
        REFERENCES tariff.product_lines(scenario_version, product_line_key),
    FOREIGN KEY (scenario_version, component_key)
        REFERENCES tariff.components(scenario_version, component_key)
);

CREATE TABLE IF NOT EXISTS tariff.suppliers (
    scenario_version VARCHAR(64) NOT NULL,
    supplier_key VARCHAR(100) NOT NULL,
    name VARCHAR(300) NOT NULL,
    is_fictional BOOLEAN NOT NULL,
    provenance_label VARCHAR(100) NOT NULL,
    source_name VARCHAR(300) NOT NULL,
    source_url TEXT,
    source_citation TEXT NOT NULL,
    PRIMARY KEY (scenario_version, supplier_key),
    FOREIGN KEY (scenario_version) REFERENCES tariff.scenario_versions(scenario_version)
);

CREATE TABLE IF NOT EXISTS tariff.countries_of_origin (
    scenario_version VARCHAR(64) NOT NULL,
    country_code CHAR(2) NOT NULL,
    name VARCHAR(100) NOT NULL,
    provenance_label VARCHAR(100) NOT NULL,
    source_name VARCHAR(300) NOT NULL,
    source_url TEXT,
    source_citation TEXT NOT NULL,
    PRIMARY KEY (scenario_version, country_code),
    FOREIGN KEY (scenario_version) REFERENCES tariff.scenario_versions(scenario_version)
);

CREATE TABLE IF NOT EXISTS tariff.supply_relationships (
    scenario_version VARCHAR(64) NOT NULL,
    supply_relationship_key VARCHAR(120) NOT NULL,
    component_key VARCHAR(100) NOT NULL,
    supplier_key VARCHAR(100) NOT NULL,
    country_code CHAR(2) NOT NULL,
    annual_spend NUMERIC(14, 2) NOT NULL CHECK (annual_spend >= 0),
    measurement_period VARCHAR(100) NOT NULL,
    provenance_label VARCHAR(100) NOT NULL,
    source_name VARCHAR(300) NOT NULL,
    source_url TEXT,
    source_citation TEXT NOT NULL,
    PRIMARY KEY (scenario_version, supply_relationship_key),
    UNIQUE (scenario_version, component_key, supplier_key, country_code, measurement_period),
    FOREIGN KEY (scenario_version, component_key)
        REFERENCES tariff.components(scenario_version, component_key),
    FOREIGN KEY (scenario_version, supplier_key)
        REFERENCES tariff.suppliers(scenario_version, supplier_key),
    FOREIGN KEY (scenario_version, country_code)
        REFERENCES tariff.countries_of_origin(scenario_version, country_code)
);

CREATE TABLE IF NOT EXISTS tariff.classification_assertions (
    scenario_version VARCHAR(64) NOT NULL,
    classification_key VARCHAR(140) NOT NULL,
    component_key VARCHAR(100) NOT NULL,
    supply_relationship_key VARCHAR(120) NOT NULL,
    sourced_variant VARCHAR(160) NOT NULL,
    jurisdiction VARCHAR(50) NOT NULL,
    schedule_period VARCHAR(50) NOT NULL,
    hts_code VARCHAR(30) NOT NULL,
    state VARCHAR(20) NOT NULL CHECK (state IN ('validated', 'candidate', 'superseded')),
    provenance_label VARCHAR(100) NOT NULL,
    source_name VARCHAR(300) NOT NULL,
    source_url TEXT,
    source_citation TEXT NOT NULL,
    PRIMARY KEY (scenario_version, classification_key),
    FOREIGN KEY (scenario_version, component_key)
        REFERENCES tariff.components(scenario_version, component_key),
    FOREIGN KEY (scenario_version, supply_relationship_key)
        REFERENCES tariff.supply_relationships(scenario_version, supply_relationship_key)
);

CREATE INDEX IF NOT EXISTS scenario_components_key_idx
    ON tariff.components(scenario_version, component_key);

CREATE INDEX IF NOT EXISTS scenario_supply_component_idx
    ON tariff.supply_relationships(scenario_version, component_key);

CREATE INDEX IF NOT EXISTS scenario_classifications_component_idx
    ON tariff.classification_assertions(scenario_version, component_key);

CREATE TABLE IF NOT EXISTS tariff.impact_outlook_snapshots (
    outlook_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id BIGINT NOT NULL REFERENCES tariff.policy_notice_snapshots(notice_id),
    policy_snapshot_version CHAR(64) NOT NULL,
    scenario_version VARCHAR(64) NOT NULL REFERENCES tariff.scenario_versions(scenario_version),
    enterprise_data_version VARCHAR(100) NOT NULL,
    classification_schedule_version VARCHAR(100) NOT NULL,
    analysis_version VARCHAR(100) NOT NULL,
    processing_state VARCHAR(20) NOT NULL CHECK (
        processing_state IN ('Queued', 'Analyzing', 'Complete', 'Failed')
    ),
    outlook_status VARCHAR(50) CHECK (
        outlook_status IN ('Action recommended', 'Validation required', 'No actionable exposure identified')
    ),
    impact_window_start DATE,
    impact_window_label TEXT NOT NULL,
    impact_window_policy_chunk_id BIGINT REFERENCES tariff.policy_notice_chunks(chunk_id),
    impact_window_policy_citation TEXT NOT NULL,
    impact_window_policy_chunk_text TEXT NOT NULL,
    annual_spend_exposed NUMERIC(14, 2) NOT NULL CHECK (annual_spend_exposed >= 0),
    spend_requiring_validation NUMERIC(14, 2) NOT NULL CHECK (spend_requiring_validation >= 0),
    affected_product_line_count INTEGER NOT NULL CHECK (affected_product_line_count >= 0),
    executive_brief TEXT NOT NULL,
    successor_of_outlook_id BIGINT REFERENCES tariff.impact_outlook_snapshots(outlook_id),
    reanalysis_sequence INTEGER NOT NULL DEFAULT 0 CHECK (reanalysis_sequence >= 0),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT impact_outlook_snapshot_status_check CHECK (
        (processing_state = 'Complete' AND outlook_status IS NOT NULL)
        OR (processing_state IN ('Queued', 'Analyzing', 'Failed') AND outlook_status IS NULL)
    ),
    CONSTRAINT impact_outlook_snapshot_input_version_key UNIQUE (
        notice_id,
        policy_snapshot_version,
        scenario_version,
        enterprise_data_version,
        classification_schedule_version,
        analysis_version,
        reanalysis_sequence
    )
);

ALTER TABLE tariff.impact_outlook_snapshots
    ADD COLUMN IF NOT EXISTS enterprise_data_version VARCHAR(100),
    ADD COLUMN IF NOT EXISTS classification_schedule_version VARCHAR(100),
    ADD COLUMN IF NOT EXISTS impact_window_start DATE,
    ADD COLUMN IF NOT EXISTS impact_window_label TEXT,
    ADD COLUMN IF NOT EXISTS impact_window_policy_chunk_id BIGINT REFERENCES tariff.policy_notice_chunks(chunk_id),
    ADD COLUMN IF NOT EXISTS impact_window_policy_citation TEXT,
    ADD COLUMN IF NOT EXISTS impact_window_policy_chunk_text TEXT,
    ADD COLUMN IF NOT EXISTS reanalysis_sequence INTEGER;

-- Remove the temporary migration defaults from earlier deployments.  They do
-- not represent deterministic input or policy evidence and legacy rows stay
-- outside the completed-Outlook replay path until genuinely backfilled.
ALTER TABLE tariff.impact_outlook_snapshots
    ALTER COLUMN enterprise_data_version DROP DEFAULT,
    ALTER COLUMN classification_schedule_version DROP DEFAULT,
    ALTER COLUMN impact_window_policy_citation DROP DEFAULT,
    ALTER COLUMN impact_window_policy_chunk_text DROP DEFAULT;

UPDATE tariff.impact_outlook_snapshots
SET reanalysis_sequence = 0
WHERE reanalysis_sequence IS NULL;

ALTER TABLE tariff.impact_outlook_snapshots
    ALTER COLUMN reanalysis_sequence SET DEFAULT 0,
    ALTER COLUMN reanalysis_sequence SET NOT NULL;

ALTER TABLE tariff.impact_outlook_snapshots
    DROP CONSTRAINT IF EXISTS impact_outlook_snapshot_reanalysis_sequence_check;

ALTER TABLE tariff.impact_outlook_snapshots
    ADD CONSTRAINT impact_outlook_snapshot_reanalysis_sequence_check
    CHECK (reanalysis_sequence >= 0);

-- Do not silently convert pre-canonical records into valid Outlooks.  The
-- migration stops until every retained legacy row has real deterministic
-- versions and policy-window evidence, after which these columns are made
-- canonical for all writes.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM tariff.impact_outlook_snapshots
        WHERE NULLIF(BTRIM(COALESCE(policy_snapshot_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(policy_snapshot_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(scenario_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(scenario_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(enterprise_data_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(enterprise_data_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(classification_schedule_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(classification_schedule_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(analysis_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(analysis_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(impact_window_label, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(impact_window_label, ''))) = 'unavailable'
           OR (
                impact_window_start IS NOT NULL
                AND (
                    impact_window_policy_chunk_id IS NULL
                    OR NULLIF(BTRIM(COALESCE(impact_window_policy_citation, '')), '') IS NULL
                    OR LOWER(BTRIM(COALESCE(impact_window_policy_citation, ''))) = 'unavailable'
                    OR NULLIF(BTRIM(COALESCE(impact_window_policy_chunk_text, '')), '') IS NULL
                    OR LOWER(BTRIM(COALESCE(impact_window_policy_chunk_text, ''))) = 'unavailable'
                )
            )
    ) THEN
        RAISE EXCEPTION USING
            MESSAGE = 'Impact Outlook migration requires backfilled canonical snapshot versions and policy-window evidence.',
            HINT = 'Backfill the retained legacy rows with genuine source facts, or preserve them outside the canonical Outlook tables before rerunning initialization.';
    END IF;
END
$$;

ALTER TABLE tariff.impact_outlook_snapshots
    ALTER COLUMN policy_snapshot_version SET NOT NULL,
    ALTER COLUMN scenario_version SET NOT NULL,
    ALTER COLUMN enterprise_data_version SET NOT NULL,
    ALTER COLUMN classification_schedule_version SET NOT NULL,
    ALTER COLUMN analysis_version SET NOT NULL,
    ALTER COLUMN impact_window_label SET NOT NULL;

ALTER TABLE tariff.impact_outlook_snapshots
    ALTER COLUMN impact_window_policy_chunk_id DROP NOT NULL,
    ALTER COLUMN impact_window_policy_citation DROP NOT NULL,
    ALTER COLUMN impact_window_policy_chunk_text DROP NOT NULL;

ALTER TABLE tariff.impact_outlook_snapshots
    DROP CONSTRAINT IF EXISTS impact_outlook_snapshots_processing_state_check;

ALTER TABLE tariff.impact_outlook_snapshots
    ADD CONSTRAINT impact_outlook_snapshots_processing_state_check
    CHECK (processing_state IN ('Queued', 'Analyzing', 'Complete', 'Failed'));

ALTER TABLE tariff.impact_outlook_snapshots
    DROP CONSTRAINT IF EXISTS impact_outlook_snapshot_status_check;

ALTER TABLE tariff.impact_outlook_snapshots
    DROP CONSTRAINT IF EXISTS impact_outlook_snapshots_check;

ALTER TABLE tariff.impact_outlook_snapshots
    ADD CONSTRAINT impact_outlook_snapshot_status_check CHECK (
        (processing_state = 'Complete' AND outlook_status IS NOT NULL)
        OR (processing_state IN ('Queued', 'Analyzing', 'Failed') AND outlook_status IS NULL)
    );

ALTER TABLE tariff.impact_outlook_snapshots
    DROP CONSTRAINT IF EXISTS impact_outlook_snapshots_notice_id_policy_snapshot_version_scenario_version_analysis_version_key;

ALTER TABLE tariff.impact_outlook_snapshots
    DROP CONSTRAINT IF EXISTS impact_outlook_snapshot_input_version_key;

ALTER TABLE tariff.impact_outlook_snapshots
    ADD CONSTRAINT impact_outlook_snapshot_input_version_key UNIQUE (
        notice_id,
        policy_snapshot_version,
        scenario_version,
        enterprise_data_version,
        classification_schedule_version,
        analysis_version,
        reanalysis_sequence
    );

CREATE INDEX IF NOT EXISTS impact_outlook_notice_idx
    ON tariff.impact_outlook_snapshots(notice_id, created_at DESC, outlook_id DESC);

CREATE TABLE IF NOT EXISTS tariff.impact_findings (
    finding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlook_id BIGINT NOT NULL REFERENCES tariff.impact_outlook_snapshots(outlook_id),
    finding_key VARCHAR(120) NOT NULL,
    product_line_key VARCHAR(100) NOT NULL,
    product_line_name VARCHAR(200) NOT NULL,
    segment_name VARCHAR(200) NOT NULL,
    annual_spend_exposed NUMERIC(14, 2) NOT NULL CHECK (annual_spend_exposed >= 0),
    spend_requiring_validation NUMERIC(14, 2) NOT NULL CHECK (spend_requiring_validation >= 0),
    UNIQUE (outlook_id, finding_key)
);

CREATE TABLE IF NOT EXISTS tariff.impact_finding_evidence_bundles (
    evidence_bundle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT NOT NULL REFERENCES tariff.impact_findings(finding_id),
    policy_chunk_id BIGINT NOT NULL REFERENCES tariff.policy_notice_chunks(chunk_id),
    policy_citation TEXT NOT NULL,
    policy_canonical_url TEXT NOT NULL,
    policy_chunk_text TEXT NOT NULL,
    hts_scope_citation TEXT NOT NULL,
    hts_scope_canonical_url TEXT NOT NULL,
    hts_scope_source_sha256 CHAR(64) NOT NULL,
    hts_scope_text TEXT NOT NULL,
    hts_scope_codes JSONB NOT NULL CONSTRAINT impact_evidence_hts_scope_codes_check CHECK (
        jsonb_typeof(hts_scope_codes) = 'array' AND hts_scope_codes <> '[]'::jsonb
    ),
    classification_evidence JSONB NOT NULL CONSTRAINT impact_evidence_classification_evidence_check CHECK (
        jsonb_typeof(classification_evidence) = 'array'
        AND classification_evidence <> '[]'::jsonb
    ),
    component_key VARCHAR(100) NOT NULL,
    component_name VARCHAR(300) NOT NULL,
    supply_relationship_key VARCHAR(120) NOT NULL,
    supplier_key VARCHAR(100) NOT NULL,
    supplier_name VARCHAR(300) NOT NULL,
    origin_code CHAR(2) NOT NULL,
    origin_name VARCHAR(100) NOT NULL,
    annual_spend NUMERIC(14, 2) NOT NULL CHECK (annual_spend >= 0),
    measurement_period VARCHAR(100) NOT NULL,
    scenario_version VARCHAR(64) NOT NULL,
    scenario_path TEXT NOT NULL,
    match_confidence VARCHAR(30) NOT NULL CHECK (
        match_confidence IN ('Direct match', 'Likely match', 'Needs validation')
    ),
    reasoning TEXT NOT NULL,
    uncertainty TEXT NOT NULL,
    UNIQUE (finding_id, supply_relationship_key)
);

CREATE INDEX IF NOT EXISTS impact_evidence_finding_idx
    ON tariff.impact_finding_evidence_bundles(finding_id, evidence_bundle_id);

ALTER TABLE tariff.impact_finding_evidence_bundles
    ADD COLUMN IF NOT EXISTS hts_scope_citation TEXT,
    ADD COLUMN IF NOT EXISTS hts_scope_canonical_url TEXT,
    ADD COLUMN IF NOT EXISTS hts_scope_source_sha256 CHAR(64),
    ADD COLUMN IF NOT EXISTS hts_scope_text TEXT,
    ADD COLUMN IF NOT EXISTS hts_scope_codes JSONB;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM tariff.impact_finding_evidence_bundles
        WHERE NULLIF(BTRIM(COALESCE(hts_scope_citation, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(hts_scope_citation, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(hts_scope_canonical_url, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(hts_scope_canonical_url, ''))) = 'unavailable'
           OR hts_scope_source_sha256 IS NULL
           OR hts_scope_source_sha256 !~ '^[0-9a-fA-F]{64}$'
           OR NULLIF(BTRIM(COALESCE(hts_scope_text, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(hts_scope_text, ''))) = 'unavailable'
           OR jsonb_typeof(hts_scope_codes) IS DISTINCT FROM 'array'
           OR hts_scope_codes = '[]'::jsonb
           OR jsonb_typeof(classification_evidence) IS DISTINCT FROM 'array'
           OR classification_evidence = '[]'::jsonb
    ) THEN
        RAISE EXCEPTION USING
            MESSAGE = 'Impact Outlook migration requires fully evidenced finding bundles.',
            HINT = 'Backfill exact HTS scope and classification evidence from the cited source, or preserve incomplete legacy findings outside the canonical evidence table before rerunning initialization.';
    END IF;
END
$$;

ALTER TABLE tariff.impact_finding_evidence_bundles
    ALTER COLUMN hts_scope_citation SET NOT NULL,
    ALTER COLUMN hts_scope_canonical_url SET NOT NULL,
    ALTER COLUMN hts_scope_source_sha256 SET NOT NULL,
    ALTER COLUMN hts_scope_text SET NOT NULL,
    ALTER COLUMN hts_scope_codes SET NOT NULL;

ALTER TABLE tariff.impact_finding_evidence_bundles
    DROP CONSTRAINT IF EXISTS impact_evidence_hts_scope_codes_check;

ALTER TABLE tariff.impact_finding_evidence_bundles
    DROP CONSTRAINT IF EXISTS impact_evidence_classification_evidence_check;

ALTER TABLE tariff.impact_finding_evidence_bundles
    ADD CONSTRAINT impact_evidence_hts_scope_codes_check CHECK (
        jsonb_typeof(hts_scope_codes) = 'array' AND hts_scope_codes <> '[]'::jsonb
    );

ALTER TABLE tariff.impact_finding_evidence_bundles
    ADD CONSTRAINT impact_evidence_classification_evidence_check CHECK (
        jsonb_typeof(classification_evidence) = 'array'
        AND classification_evidence <> '[]'::jsonb
    );

CREATE TABLE IF NOT EXISTS tariff.recommended_actions (
    recommended_action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlook_id BIGINT NOT NULL REFERENCES tariff.impact_outlook_snapshots(outlook_id),
    action_key VARCHAR(80) NOT NULL CHECK (action_key IN (
        'validate_classification_or_origin',
        'request_supplier_confirmation_or_quote',
        'evaluate_alternate_sourcing',
        'review_inventory_or_pre_buy_feasibility',
        'assess_product_pricing'
    )),
    title VARCHAR(200) NOT NULL,
    priority SMALLINT NOT NULL CHECK (priority BETWEEN 1 AND 3),
    is_conditional BOOLEAN NOT NULL,
    evidence_relationship_keys JSONB NOT NULL,
    UNIQUE (outlook_id, action_key),
    UNIQUE (outlook_id, priority)
);

CREATE TABLE IF NOT EXISTS tariff.agent_runs (
    agent_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(320) NOT NULL,
    operation VARCHAR(80) NOT NULL,
    requested_notice_id BIGINT NOT NULL,
    notice_id BIGINT REFERENCES tariff.policy_notice_snapshots(notice_id),
    outlook_id BIGINT REFERENCES tariff.impact_outlook_snapshots(outlook_id),
    policy_snapshot_version CHAR(64),
    snapshot_obtained BOOLEAN NOT NULL,
    scenario_version VARCHAR(64) NOT NULL,
    enterprise_data_version VARCHAR(100) NOT NULL,
    classification_schedule_version VARCHAR(100) NOT NULL,
    analysis_version VARCHAR(100) NOT NULL,
    model_version VARCHAR(200) NOT NULL,
    prompt_version VARCHAR(200) NOT NULL,
    processing_state VARCHAR(20) NOT NULL CONSTRAINT agent_run_processing_state_check CHECK (
        processing_state IN ('Queued', 'Analyzing', 'Complete', 'Failed')
    ),
    outcome VARCHAR(100) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    error_boundary VARCHAR(200),
    retry_predecessor_run_id BIGINT REFERENCES tariff.agent_runs(agent_run_id),
    CHECK (completed_at >= started_at),
    CONSTRAINT agent_run_snapshot_state_check CHECK (
        (snapshot_obtained AND notice_id IS NOT NULL
            AND policy_snapshot_version ~ '^[0-9a-fA-F]{64}$')
        OR (NOT snapshot_obtained AND notice_id IS NULL AND policy_snapshot_version IS NULL)
    )
);

ALTER TABLE tariff.agent_runs
    ADD COLUMN IF NOT EXISTS requested_notice_id BIGINT,
    ADD COLUMN IF NOT EXISTS snapshot_obtained BOOLEAN,
    ADD COLUMN IF NOT EXISTS enterprise_data_version VARCHAR(100),
    ADD COLUMN IF NOT EXISTS classification_schedule_version VARCHAR(100),
    ADD COLUMN IF NOT EXISTS error_boundary VARCHAR(200);

ALTER TABLE tariff.agent_runs
    ALTER COLUMN enterprise_data_version DROP DEFAULT,
    ALTER COLUMN classification_schedule_version DROP DEFAULT;

-- Existing runs with a real snapshot can be backfilled from their immutable
-- foreign key. Runs with a missing or sentinel snapshot version remain blocked
-- for explicit remediation rather than being misrepresented as pre-snapshot.
UPDATE tariff.agent_runs
SET requested_notice_id = notice_id,
    snapshot_obtained = TRUE
WHERE requested_notice_id IS NULL
  AND notice_id IS NOT NULL
  AND policy_snapshot_version ~ '^[0-9a-fA-F]{64}$';

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM tariff.agent_runs
        WHERE requested_notice_id IS NULL
           OR snapshot_obtained IS NULL
           OR (
                snapshot_obtained
                AND (
                    notice_id IS NULL
                    OR policy_snapshot_version IS NULL
                    OR policy_snapshot_version !~ '^[0-9a-fA-F]{64}$'
                )
           )
           OR (
                NOT snapshot_obtained
                AND (notice_id IS NOT NULL OR policy_snapshot_version IS NOT NULL)
           )
           OR NULLIF(BTRIM(COALESCE(scenario_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(scenario_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(enterprise_data_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(enterprise_data_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(classification_schedule_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(classification_schedule_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(analysis_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(analysis_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(model_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(model_version, ''))) = 'unavailable'
           OR NULLIF(BTRIM(COALESCE(prompt_version, '')), '') IS NULL
           OR LOWER(BTRIM(COALESCE(prompt_version, ''))) = 'unavailable'
    ) THEN
        RAISE EXCEPTION USING
            MESSAGE = 'Agent Run migration requires canonical attempt state and version records.',
            HINT = 'Backfill every retained snapshot-obtained Agent Run with genuine input, model, and prompt versions; explicitly model pre-snapshot attempts before rerunning initialization.';
    END IF;
END
$$;

ALTER TABLE tariff.agent_runs
    ALTER COLUMN requested_notice_id SET NOT NULL,
    ALTER COLUMN snapshot_obtained SET NOT NULL,
    ALTER COLUMN scenario_version SET NOT NULL,
    ALTER COLUMN enterprise_data_version SET NOT NULL,
    ALTER COLUMN classification_schedule_version SET NOT NULL,
    ALTER COLUMN analysis_version SET NOT NULL,
    ALTER COLUMN model_version SET NOT NULL,
    ALTER COLUMN prompt_version SET NOT NULL;

ALTER TABLE tariff.agent_runs
    ALTER COLUMN notice_id DROP NOT NULL,
    ALTER COLUMN policy_snapshot_version DROP NOT NULL;

ALTER TABLE tariff.agent_runs
    DROP CONSTRAINT IF EXISTS agent_runs_processing_state_check;

ALTER TABLE tariff.agent_runs
    DROP CONSTRAINT IF EXISTS agent_run_processing_state_check;

ALTER TABLE tariff.agent_runs
    DROP CONSTRAINT IF EXISTS agent_run_snapshot_state_check;

ALTER TABLE tariff.agent_runs
    ADD CONSTRAINT agent_run_processing_state_check CHECK (
        processing_state IN ('Queued', 'Analyzing', 'Complete', 'Failed')
    );

ALTER TABLE tariff.agent_runs
    ADD CONSTRAINT agent_run_snapshot_state_check CHECK (
        (snapshot_obtained AND notice_id IS NOT NULL
            AND policy_snapshot_version ~ '^[0-9a-fA-F]{64}$')
        OR (NOT snapshot_obtained AND notice_id IS NULL AND policy_snapshot_version IS NULL)
    );

CREATE INDEX IF NOT EXISTS agent_runs_notice_idx
    ON tariff.agent_runs(notice_id, started_at DESC, agent_run_id DESC);

CREATE TABLE IF NOT EXISTS tariff.agent_tool_events (
    agent_tool_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id BIGINT NOT NULL REFERENCES tariff.agent_runs(agent_run_id),
    event_index SMALLINT NOT NULL CHECK (event_index BETWEEN 1 AND 3),
    tool_name VARCHAR(100) NOT NULL CHECK (tool_name IN (
        'retrieve_policy_notice_snapshot',
        'find_exposure_candidates',
        'retrieve_demonstration_scenario_context'
    )),
    tool_version VARCHAR(50) NOT NULL,
    input_summary JSONB NOT NULL,
    output_summary JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    UNIQUE (agent_run_id, event_index),
    UNIQUE (agent_run_id, tool_name)
);

CREATE TABLE IF NOT EXISTS tariff.agent_actions (
    agent_action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_run_id BIGINT NOT NULL REFERENCES tariff.agent_runs(agent_run_id),
    action_kind VARCHAR(80) NOT NULL,
    action_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
